### ISSUE TITLE
How to deploy this?

### ISSUE THREAD

**Issue by uhlhosting** [pulinairc/thelounge-themes#1]
Hi,

I tried to follow your steps, still somehow cant seem to figure out how to get to the themes.

```
.vcm@mdb:/etc/thelounge/public/themes$ ls
auto-day-midnight.css      day.css      midnight-accessible.css      midnight-classic-mobile.css      midnight.css      thelounge-themes
auto-day-midnight.css.map  day.css.map  midnight-accessible.css.map  midnight-classic-mobile.css.map  midnight.css.map
vcm@mdb:/etc/thelounge/public/themes$ pwd
/etc/thelounge/public/themes
```

**Comment by rollecode** [comment]
Looks like they are in the correct place. After placing the themes you need to restart thelounge instance to see them in the settings menu. Did you already restart?

**Comment by uhlhosting** [comment]
> Looks like they are in the correct place. After placing the themes you need to restart thelounge instance to see them in the settings menu. Did you already restart?

yes I restarted and did not helped.

**Comment by rollecode** [comment]
Then it's really hard to say. Do you run your thelounge from /etc/thelounge manually or do you use the public package? The themes should be really in the same copy where you are running the instance. I am for example running thelounge from home dir. If you install thelounge via npm it can be anywhere based on the system. Find out your instances by running `which thelounge` and `sudo find / -name 'thelounge'`. As long as themes are in the right dir it should work.

``` shell
[07:55:52] rolle@pulina themes $ pwd
/home/rolle/thelounge/public/themes
[07:56:24] rolle@pulina themes $ sudo ls -la
total 176
drwxrwxr-x 3 rolle rolle  4096 Feb 27 18:46 .
drwxrwxr-x 8 rolle rolle  4096 Feb 16 23:50 ..
-rwxrwxr-x 1 rolle rolle 14138 Feb 23 10:46 amoled.css
-rw-rw-r-- 1 rolle rolle 25394 Feb 26 23:11 auto-day-midnight.css
-rw-rw-r-- 1 rolle rolle  7670 Feb 27 00:45 day.css
-rwxrwxr-x 1 rolle rolle   380 Feb 22 21:33 default.css
-rwxrwxr-x 1 rolle rolle 14736 Feb 23 10:46 dracula.css
drwxrwxr-x 2 rolle rolle 12288 Feb 18 08:57 fonts
-rw-rw-r-- 1 rolle rolle 21187 Mar  1 14:04 midnight-accessible.css
-rw-rw-r-- 1 rolle rolle 15714 Feb 27 18:43 midnight-classic-mobile.css
-rw-rw-r-- 1 rolle rolle 20513 Mar  1 14:02 midnight.css
lrwxrwxrwx 1 rolle rolle     7 Feb 27 18:46 modern.css -> day.css
-rwxrwxr-x 1 rolle rolle  4110 Feb 22 21:33 morning.css
-rwxrwxr-x 1 rolle rolle  9472 Feb 23 10:46 night.css
[07:56:26] rolle@pulina themes $ 
```
